#!/usr/bin/env python3
"""Regenerate add-chamber-light-gcode-1.4.49.bsdiff AND verify-1.4.49.py together.

Usage: generate_patch.py <stock-app> <patched-app>

Run this whenever the 1.4.49 handler bodies are re-assembled. It rewrites both
artifacts from the same input pair so the byte guard can never go stale against
the bsdiff. Guard spans cover every changed region (regions separated by less
than 32 unchanged bytes are merged).
"""
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
MERGE_GAP = 32


def changed_spans(a: bytes, b: bytes, merge_gap: int):
    diffs = [i for i in range(min(len(a), len(b))) if a[i] != b[i]]
    if not diffs:
        return []
    spans = [[diffs[0], diffs[0] + 1]]
    for i in diffs[1:]:
        if i - spans[-1][1] < merge_gap:
            spans[-1][1] = i + 1
        else:
            spans.append([i, i + 1])
    return spans


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    stock = Path(sys.argv[1]).read_bytes()
    patched = Path(sys.argv[2]).read_bytes()
    if len(stock) != len(patched):
        print("error: patched binary size differs from stock; same-length expected")
        return 1

    spans = changed_spans(stock, patched, MERGE_GAP)
    if not spans:
        print("error: binaries are identical, nothing to patch")
        return 1
    print(f"{len(spans)} guard span(s): " + ", ".join(f"0x{s:x}..0x{e:x}" for s, e in spans))

    bsdiff_path = HERE / "add-chamber-light-gcode-1.4.49.bsdiff"
    subprocess.run(["bsdiff", sys.argv[1], sys.argv[2], str(bsdiff_path)], check=True)

    entries = []
    for s, e in spans:
        entries.append(
            f"    0x{s:X}: (\n"
            f"        bytes.fromhex(\"{stock[s:e].hex()}\"),\n"
            f"        bytes.fromhex(\"{patched[s:e].hex()}\"),\n"
            f"    ),"
        )
    body = VERIFY_TEMPLATE.replace("__SPANS__", "\n".join(entries))
    (HERE / "verify-1.4.49.py").write_text(body)
    print(f"wrote {bsdiff_path.name} and verify-1.4.49.py")
    return 0


VERIFY_TEMPLATE = '''#!/usr/bin/env python3
"""Verify the bytes add-chamber-light-gcode-1.4.49.bsdiff touches.

Usage: verify-1.4.49.py <path-to-app> [before|after]

'before' (default): the guarded spans must match stock 1.4.49 bytes, i.e. it is
safe to apply the bsdiff. 'after': the spans must match the patched bodies.
Bytes outside these spans are not checked.

Regenerated by generate_patch.py - do not edit spans by hand.
"""
import sys

SPANS = {
__SPANS__
}


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    path = sys.argv[1]
    mode = sys.argv[2] if len(sys.argv) > 2 else "before"
    if mode not in ("before", "after"):
        print(f"error: unknown mode {mode!r} (want before|after)")
        return 2
    want_idx = 0 if mode == "before" else 1

    with open(path, "rb") as fp:
        data = fp.read()

    failed = False
    for off, spans in SPANS.items():
        want = spans[want_idx]
        got = data[off:off + len(want)]
        label = f"span at file 0x{off:08x}"
        if got != want:
            bad = next(i for i, (a, b) in enumerate(zip(got, want)) if a != b)
            print(
                f"error: {label} does not match expected {mode} bytes "
                f"(first diff at +0x{bad:x}: got 0x{got[bad]:02x}, want 0x{want[bad]:02x}). "
                f"Refusing to proceed."
            )
            failed = True
    if failed:
        return 1
    print(f"verify-1.4.49: all guarded spans match expected {mode} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


if __name__ == "__main__":
    sys.exit(main())
