#!/usr/bin/env python3
"""Verify the bytes add-chamber-light-gcode-1.4.49.bsdiff touches.

Usage: verify-1.4.49.py <path-to-app> [before|after]

'before' (default): the guarded spans must match stock 1.4.49 bytes, i.e. it is
safe to apply the bsdiff. 'after': the spans must match the patched bodies.
Bytes outside these spans are not checked.

Regenerated by generate_patch.py - do not edit spans by hand.
"""
import sys

SPANS = {
    0x95D98: (
        bytes.fromhex("0030d0e5000053e31eff2f1170402de9bc4702e34b4040e3003094e5000053e30200000ac00193e57040bde8435806ea260ea0e3cbd5fdeb0050a0"),
        bytes.fromhex("70402de9bc4702e34b4040e30000a0e38a3d09eb003094e5000053e30400000a180293e5000050e30100000a0010a0e3ffc403eb7040bde81eff2f"),
    ),
    0x95E50: (
        bytes.fromhex("0030d0e5000053e31eff2f1170402de9bc4702e34b4040e3003094e5000053e30200000ac00193e57040bde8155806ea260ea0e39dd5fdeb0050a0"),
        bytes.fromhex("70402de9bc4702e34b4040e30100a0e35c3d09eb003094e5000053e30400000a180293e5000050e30100000a0110a0e3d1c403eb7040bde81eff2f"),
    ),
}


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    path = sys.argv[1]
    mode = sys.argv[2] if len(sys.argv) > 2 else "before"
    if mode not in ("before", "after"):
        print(f"error: unknown mode {mode!r} (want before|after)")
        return 2
    want_idx = 0 if mode == "before" else 1

    with open(path, "rb") as fp:
        data = fp.read()

    failed = False
    for off, spans in SPANS.items():
        want = spans[want_idx]
        got = data[off:off + len(want)]
        label = f"span at file 0x{off:08x}"
        if got != want:
            bad = next(i for i, (a, b) in enumerate(zip(got, want)) if a != b)
            print(
                f"error: {label} does not match expected {mode} bytes "
                f"(first diff at +0x{bad:x}: got 0x{got[bad]:02x}, want 0x{want[bad]:02x}). "
                f"Refusing to proceed."
            )
            failed = True
    if failed:
        return 1
    print(f"verify-1.4.49: all guarded spans match expected {mode} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
